#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script pour traduire automatiquement tous les noms de Pokémon en français
dans les fichiers species_info.
"""

import os
import re
import sys

# Dictionnaire des traductions officielle des Pokémon en français
POKEMON_TRANSLATIONS = {
    # Génération 1 (Kanto)
    "Bulbasaur": "Bulbizarre",
    "Ivysaur": "Herbizarre",
    "Venusaur": "Florizarre",
    "Charmander": "Salamèche",
    "Charmeleon": "Reptincel",
    "Charizard": "Dracaufeu",
    "Squirtle": "Carapuce",
    "Wartortle": "Carabaffe",
    "Blastoise": "Tortank",
    "Caterpie": "Chenipan",
    "Metapod": "Chrysacier",
    "Butterfree": "Papilusion",
    "Weedle": "Aspicot",
    "Kakuna": "Coconfort",
    "Beedrill": "Dardargnan",
    "Pidgey": "Roucool",
    "Pidgeotto": "Roucoups",
    "Pidgeot": "Roucarnage",
    "Rattata": "Rattata",
    "Raticate": "Rattatac",
    "Spearow": "Piafabec",
    "Fearow": "Rapasdepic",
    "Ekans": "Abo",
    "Arbok": "Arbok",
    "Pikachu": "Pikachu",
    "Raichu": "Raichu",
    "Sandshrew": "Sabelette",
    "Sandslash": "Sablaireau",
    "Nidoran♀": "Nidoran♀",
    "Nidorina": "Nidorina",
    "Nidoqueen": "Nidoqueen",
    "Nidoran♂": "Nidoran♂",
    "Nidorino": "Nidorino",
    "Nidoking": "Nidoking",
    "Clefairy": "Mélofée",
    "Clefable": "Mélodelfe",
    "Vulpix": "Goupix",
    "Ninetales": "Feunard",
    "Jigglypuff": "Rondoudou",
    "Wigglytuff": "Grodoudou",
    "Zubat": "Nosferapti",
    "Golbat": "Nosferalto",
    "Oddish": "Mystherbe",
    "Gloom": "Ortide",
    "Vileplume": "Rafflesia",
    "Paras": "Paras",
    "Parasect": "Parasect",
    "Venonat": "Mimitoss",
    "Venomoth": "Aéromite",
    "Diglett": "Taupiqueur",
    "Dugtrio": "Triopikeur",
    "Meowth": "Miaouss",
    "Persian": "Persian",
    "Psyduck": "Psykokwak",
    "Golduck": "Akwakwak",
    "Mankey": "Férosinge",
    "Primeape": "Colossinge",
    "Growlithe": "Caninos",
    "Arcanine": "Arcanin",
    "Poliwag": "Ptitard",
    "Poliwhirl": "Têtarte",
    "Poliwrath": "Tartard",
    "Abra": "Abra",
    "Kadabra": "Kadabra",
    "Alakazam": "Alakazam",
    "Machop": "Machoc",
    "Machoke": "Machopeur",
    "Machamp": "Mackogneur",
    "Bellsprout": "Chétiflor",
    "Weepinbell": "Boustiflor",
    "Victreebel": "Empiflor",
    "Tentacool": "Tentacool",
    "Tentacruel": "Tentacruel",
    "Geodude": "Racaillou",
    "Graveler": "Gravalanch",
    "Golem": "Grolem",
    "Ponyta": "Ponyta",
    "Rapidash": "Galopa",
    "Slowpoke": "Ramoloss",
    "Slowbro": "Flagadoss",
    "Magnemite": "Magnéti",
    "Magneton": "Magnéton",
    "Farfetch'd": "Canarticho",
    "Doduo": "Doduo",
    "Dodrio": "Dodrio",
    "Seel": "Otaria",
    "Dewgong": "Lamantine",
    "Grimer": "Tadmorv",
    "Muk": "Grotadmorv",
    "Shellder": "Kokiyas",
    "Cloyster": "Crustabri",
    "Gastly": "Fantominus",
    "Haunter": "Spectrum",
    "Gengar": "Ectoplasma",
    "Onix": "Onix",
    "Drowzee": "Soporifik",
    "Hypno": "Hypnomade",
    "Krabby": "Krabby",
    "Kingler": "Krabboss",
    "Voltorb": "Voltorbe",
    "Electrode": "Électrode",
    "Exeggcute": "Noeunoeuf",
    "Exeggutor": "Noadkoko",
    "Cubone": "Osselait",
    "Marowak": "Ossatueur",
    "Hitmonlee": "Kicklee",
    "Hitmonchan": "Tygnon",
    "Lickitung": "Excelangue",
    "Koffing": "Smogo",
    "Weezing": "Smogogo",
    "Rhyhorn": "Rhinocorne",
    "Rhydon": "Rhinoféros",
    "Chansey": "Leveinard",
    "Tangela": "Saquedeneu",
    "Kangaskhan": "Kangourex",
    "Horsea": "Hypotrempe",
    "Seadra": "Hypocéan",
    "Goldeen": "Poissirène",
    "Seaking": "Poissoroy",
    "Staryu": "Stari",
    "Starmie": "Staross",
    "Mr. Mime": "M. Mime",
    "Scyther": "Insécateur",
    "Jynx": "Lippoutou",
    "Electabuzz": "Élektek",
    "Magmar": "Magmar",
    "Pinsir": "Scarabrute",
    "Tauros": "Tauros",
    "Magikarp": "Magicarpe",
    "Gyarados": "Léviator",
    "Lapras": "Lokhlass",
    "Ditto": "Métamorph",
    "Eevee": "Évoli",
    "Vaporeon": "Aquali",
    "Jolteon": "Voltali",
    "Flareon": "Pyroli",
    "Porygon": "Porygon",
    "Omanyte": "Amonita",
    "Omastar": "Amonistar",
    "Kabuto": "Kabuto",
    "Kabutops": "Kabutops",
    "Aerodactyl": "Ptéra",
    "Snorlax": "Ronflex",
    "Articuno": "Artikodin",
    "Zapdos": "Électhor",
    "Moltres": "Sulfura",
    "Dratini": "Minidraco",
    "Dragonair": "Draco",
    "Dragonite": "Dracolosse",
    "Mewtwo": "Mewtwo",
    "Mew": "Mew",

    # Génération 2 (Johto)
    "Chikorita": "Germignon",
    "Bayleef": "Macronium",
    "Meganium": "Méganium",
    "Cyndaquil": "Héricendre",
    "Quilava": "Feurisson",
    "Typhlosion": "Typhlosion",
    "Totodile": "Kaiminus",
    "Croconaw": "Crocrodil",
    "Feraligatr": "Aligatueur",
    "Sentret": "Fouinette",
    "Furret": "Fouinar",
    "Hoothoot": "Hoothoot",
    "Noctowl": "Noarfang",
    "Ledyba": "Coxy",
    "Ledian": "Coxyclaque",
    "Spinarak": "Mimigal",
    "Ariados": "Migalos",
    "Crobat": "Nostenfer",
    "Chinchou": "Loupio",
    "Lanturn": "Lanturn",
    "Pichu": "Pichu",
    "Cleffa": "Mélo",
    "Igglybuff": "Toudoudou",
    "Togepi": "Togepi",
    "Togetic": "Togetic",
    "Natu": "Natu",
    "Xatu": "Xatu",
    "Mareep": "Wattouat",
    "Flaaffy": "Lainergie",
    "Ampharos": "Pharamp",
    "Bellossom": "Joliflor",
    "Marill": "Marill",
    "Azumarill": "Azumarill",
    "Sudowoodo": "Simularbre",
    "Politoed": "Tarpaud",
    "Hoppip": "Granivol",
    "Skiploom": "Floravol",
    "Jumpluff": "Cotovol",
    "Aipom": "Capumain",
    "Sunkern": "Tournegrin",
    "Sunflora": "Héliatronc",
    "Yanma": "Yanma",
    "Wooper": "Axoloto",
    "Quagsire": "Maraiste",
    "Espeon": "Mentali",
    "Umbreon": "Noctali",
    "Murkrow": "Cornèbre",
    "Slowking": "Roigada",
    "Misdreavus": "Feuforêve",
    "Unown": "Zarbi",
    "Wobbuffet": "Qulbutoké",
    "Girafarig": "Girafarig",
    "Pineco": "Pomdepik",
    "Forretress": "Foretress",
    "Dunsparce": "Insolourdo",
    "Gligar": "Scorplane",
    "Steelix": "Steelix",
    "Snubbull": "Snubbull",
    "Granbull": "Granbull",
    "Qwilfish": "Qwilfish",
    "Scizor": "Cizayox",
    "Shuckle": "Caratroc",
    "Heracross": "Scarhino",
    "Sneasel": "Farfuret",
    "Teddiursa": "Teddiursa",
    "Ursaring": "Ursaring",
    "Slugma": "Limagma",
    "Magcargo": "Volcaropod",
    "Swinub": "Marcacrin",
    "Piloswine": "Cochignon",
    "Corsola": "Corayon",
    "Remoraid": "Rémoraid",
    "Octillery": "Octillery",
    "Delibird": "Cadoizo",
    "Mantine": "Démanta",
    "Skarmory": "Airmure",
    "Houndour": "Malosse",
    "Houndoom": "Démolosse",
    "Kingdra": "Hyporoi",
    "Phanpy": "Phanpy",
    "Donphan": "Donphan",
    "Porygon2": "Porygon2",
    "Stantler": "Cerfrousse",
    "Smeargle": "Queulorior",
    "Tyrogue": "Debugant",
    "Hitmontop": "Kapoera",
    "Smoochum": "Lippouti",
    "Elekid": "Élekid",
    "Magby": "Magby",
    "Miltank": "Écrémeuh",
    "Blissey": "Leuphorie",
    "Raikou": "Raikou",
    "Entei": "Entei",
    "Suicune": "Suicune",
    "Larvitar": "Embrylex",
    "Pupitar": "Ymphect",
    "Tyranitar": "Tyranocif",
    "Lugia": "Lugia",
    "Ho-Oh": "Ho-Oh",
    "Celebi": "Celebi",

    # Génération 3 (Hoenn)
    "Treecko": "Arcko",
    "Grovyle": "Massko", 
    "Sceptile": "Jungko",
    "Torchic": "Poussifeu",
    "Combusken": "Galifeu",
    "Blaziken": "Braségali",
    "Mudkip": "Gobou",
    "Marshtomp": "Fangshimp",
    "Swampert": "Laggron",
    "Poochyena": "Medhyèna",
    "Mightyena": "Grahyèna",
    "Zigzagoon": "Zigzaton",
    "Linoone": "Linéon",
    "Wurmple": "Chenipotte",
    "Silcoon": "Armulys",
    "Beautifly": "Charmillon",
    "Cascoon": "Blindalys",
    "Dustox": "Papinox",
    "Lotad": "Nénupiot",
    "Lombre": "Lombre",
    "Ludicolo": "Ludicolo",
    "Seedot": "Grainipiot",
    "Nuzleaf": "Pifeuil",
    "Shiftry": "Tengalice",
    "Taillow": "Nirondelle",
    "Swellow": "Hélédelle",
    "Wingull": "Goélise",
    "Pelipper": "Békipan",
    "Ralts": "Tarsal",
    "Kirlia": "Kirlia",
    "Gardevoir": "Gardevoir",
    "Surskit": "Arakdo",
    "Masquerain": "Maskadra",
    "Shroomish": "Balignon",
    "Breloom": "Chapignon",
    "Slakoth": "Parecool",
    "Vigoroth": "Vigoroth",
    "Slaking": "Monaflèmit",
    "Nincada": "Ningale",
    "Ninjask": "Ninjask",
    "Shedinja": "Munja",
    "Whismur": "Chuchmur",
    "Loudred": "Ramboum",
    "Exploud": "Brouhabam",
    "Makuhita": "Makuhita",
    "Hariyama": "Hariyama",
    "Azurill": "Azurill",
    "Nosepass": "Tarinor",
    "Skitty": "Skitty",
    "Delcatty": "Delcatty",
    "Sableye": "Ténéfix",
    "Mawile": "Mysdibule",
    "Aron": "Galekid",
    "Lairon": "Galegon",
    "Aggron": "Galeking",
    "Meditite": "Méditikka",
    "Medicham": "Charmina",
    "Electrike": "Dynavolt",
    "Manectric": "Élecsprint",
    "Plusle": "Posipi",
    "Minun": "Négapi",
    "Volbeat": "Muciole",
    "Illumise": "Lumivole",
    "Roselia": "Rosélia",
    "Gulpin": "Gloupti",
    "Swalot": "Avaltout",
    "Carvanha": "Carvanha",
    "Sharpedo": "Sharpedo",
    "Wailmer": "Wailmer",
    "Wailord": "Wailord",
    "Numel": "Chamallot",
    "Camerupt": "Camérupt",
    "Torkoal": "Chartor",
    "Spoink": "Spoink",
    "Grumpig": "Groret",
    "Spinda": "Spinda",
    "Trapinch": "Kraknoix",
    "Vibrava": "Vibraninf",
    "Flygon": "Libégon",
    "Cacnea": "Cacnea",
    "Cacturne": "Cacturne",
    "Swablu": "Tylton",
    "Altaria": "Altaria",
    "Zangoose": "Mangriff",
    "Seviper": "Séviper",
    "Lunatone": "Séléroc",
    "Solrock": "Solaroc",
    "Barboach": "Barloche",
    "Whiscash": "Barbicha",
    "Corphish": "Écrapince",
    "Crawdaunt": "Colhomard",
    "Baltoy": "Balbuto",
    "Claydol": "Kaorine",
    "Lileep": "Lilia",
    "Cradily": "Vacilys",
    "Anorith": "Anorith",
    "Armaldo": "Armaldo",
    "Feebas": "Barpau",
    "Milotic": "Milobellus",
    "Castform": "Morphéo",
    "Kecleon": "Kecleon",
    "Shuppet": "Polichombr",
    "Banette": "Branette",
    "Duskull": "Skelénox",
    "Dusclops": "Téraclope",
    "Tropius": "Tropius",
    "Chimecho": "Éoko",
    "Absol": "Absol",
    "Wynaut": "Okeoke",
    "Snorunt": "Stalgamin",
    "Glalie": "Oniglali",
    "Spheal": "Obalie",
    "Sealeo": "Phogleur",
    "Walrein": "Kaimorse",
    "Clamperl": "Coquiperl",
    "Huntail": "Serpang",
    "Gorebyss": "Rosabyss",
    "Relicanth": "Relicanth",
    "Luvdisc": "Lovdisc",
    "Bagon": "Draby",
    "Shelgon": "Drackhaus",
    "Salamence": "Drattak",
    "Beldum": "Terhal",
    "Metang": "Métang",
    "Metagross": "Métalosse",
    "Regirock": "Regirock",
    "Regice": "Regice",
    "Registeel": "Registeel",
    "Latias": "Latias",
    "Latios": "Latios",
    "Kyogre": "Kyogre",
    "Groudon": "Groudon",
    "Rayquaza": "Rayquaza",
    "Jirachi": "Jirachi",
    "Deoxys": "Deoxys",

    # Génération 4 (Sinnoh)
    "Turtwig": "Tortipouss",
    "Grotle": "Boskara",
    "Torterra": "Torterra",
    "Chimchar": "Ouisticram",
    "Monferno": "Chimpenfeu",
    "Infernape": "Simiabraz",
    "Piplup": "Tiplouf",
    "Prinplup": "Prinplouf",
    "Empoleon": "Pingoléon",
    "Starly": "Étourmi",
    "Staravia": "Étourvol",
    "Staraptor": "Étouraptor",
    "Bidoof": "Keunotor",
    "Bibarel": "Castorno",
    "Kricketot": "Crikzik",
    "Kricketune": "Mélokrik",
    "Shinx": "Lixy",
    "Luxio": "Luxio",
    "Luxray": "Luxray",
    "Budew": "Rozbouton",
    "Roserade": "Roserade",
    "Cranidos": "Kranidos",
    "Rampardos": "Charkos",
    "Shieldon": "Dinoclier",
    "Bastiodon": "Bastiodon",
    "Burmy": "Cheniti",
    "Wormadam": "Cheniselle",
    "Mothim": "Papilord",
    "Combee": "Apitrini",
    "Vespiquen": "Apireine",
    "Pachirisu": "Pachirisu",
    "Buizel": "Mustébouée",
    "Floatzel": "Mustéflott",
    "Cherubi": "Ceribou",
    "Cherrim": "Ceriflor",
    "Shellos": "Sancoki",
    "Gastrodon": "Tritosor",
    "Ambipom": "Capidextre",
    "Drifloon": "Baudrive",
    "Drifblim": "Grodrive",
    "Buneary": "Laporeille",
    "Lopunny": "Lockpin",
    "Mismagius": "Magirêve",
    "Honchkrow": "Corboss",
    "Glameow": "Chaglam",
    "Purugly": "Chaffreux",
    "Chingling": "Korillon",
    "Stunky": "Moufouette",
    "Skuntank": "Moufflair",
    "Bronzor": "Archéomire",
    "Bronzong": "Archéodong",
    "Bonsly": "Manzaï",
    "Mime Jr.": "Mime Jr.",
    "Happiny": "Ptiravi",
    "Chatot": "Pijako",
    "Spiritomb": "Spiritomb",
    "Gible": "Griknot",
    "Gabite": "Carmache",
    "Garchomp": "Carchacrok",
    "Munchlax": "Goinfrex",
    "Riolu": "Riolu",
    "Lucario": "Lucario",
    "Hippopotas": "Hippopotas",
    "Hippowdon": "Hippodocus",
    "Skorupi": "Rapion",
    "Drapion": "Drascore",
    "Croagunk": "Cradopaud",
    "Toxicroak": "Coatox",
    "Carnivine": "Vortente",
    "Finneon": "Écayon",
    "Lumineon": "Luminéon",
    "Mantyke": "Babimanta",
    "Snover": "Blizzi",
    "Abomasnow": "Blizzaroi",
    "Weavile": "Dimoret",
    "Magnezone": "Magnézone",
    "Lickilicky": "Coudlangue",
    "Rhyperior": "Rhinastoc",
    "Tangrowth": "Bouldeneu",
    "Electivire": "Élekable",
    "Magmortar": "Maganon",
    "Togekiss": "Togekiss",
    "Yanmega": "Yanméga",
    "Leafeon": "Phyllali",
    "Glaceon": "Givrali",
    "Gliscor": "Scorvol",
    "Mamoswine": "Mammochon",
    "Porygon-Z": "Porygon-Z",
    "Gallade": "Gallame",
    "Probopass": "Tarinorme",
    "Dusknoir": "Noctunoir",
    "Froslass": "Momartik",
    "Rotom": "Motisma",
    "Uxie": "Créhelf",
    "Mesprit": "Créfollet",
    "Azelf": "Créfadet",
    "Dialga": "Dialga",
    "Palkia": "Palkia",
    "Heatran": "Heatran",
    "Regigigas": "Regigigas",
    "Giratina": "Giratina",
    "Cresselia": "Cresselia",
    "Phione": "Phione",
    "Manaphy": "Manaphy",
    "Darkrai": "Darkrai",
    "Shaymin": "Shaymin",
    "Arceus": "Arceus",

    # Génération 5 (Unys)
    "Victini": "Victini",
    "Snivy": "Vipélierre",
    "Servine": "Lianaja",
    "Serperior": "Majaspic",
    "Tepig": "Gruikui",
    "Pignite": "Grotichon",
    "Emboar": "Roitiflam",
    "Oshawott": "Moustillon",
    "Dewott": "Mateloutre",
    "Samurott": "Clamiral",
    "Patrat": "Ratentif",
    "Watchog": "Miradar",
    "Lillipup": "Ponchiot",
    "Herdier": "Ponchien",
    "Stoutland": "Mastouffe",
    "Purrloin": "Chacripan",
    "Liepard": "Léopardus",
    "Pansage": "Feuillajou",
    "Simisage": "Feuiloutan",
    "Pansear": "Flamajou",
    "Simisear": "Flamoutan",
    "Panpour": "Flotajou",
    "Simipour": "Flotoutan",
    "Munna": "Munna",
    "Musharna": "Mushana",
    "Pidove": "Poichigeon",
    "Tranquill": "Colombeau",
    "Unfezant": "Déflaisan",
    "Blitzle": "Zébibron",
    "Zebstrika": "Zéblitz",
    "Roggenrola": "Nodulithe",
    "Boldore": "Géolithe",
    "Gigalith": "Gigalithe",
    "Woobat": "Chovsourir",
    "Swoobat": "Rhinolove",
    "Drilbur": "Rototaupe",
    "Excadrill": "Minotaupe",
    "Audino": "Nanméouïe",
    "Timburr": "Charpenti",
    "Gurdurr": "Ouvrifier",
    "Conkeldurr": "Bétochef",
    "Tympole": "Tritonde",
    "Palpitoad": "Batracné",
    "Seismitoad": "Crapustule",
    "Throh": "Judokrak",
    "Sawk": "Karaclée",
    "Sewaddle": "Larveyette",
    "Swadloon": "Couverdure",
    "Leavanny": "Manternel",
    "Venipede": "Venipatte",
    "Whirlipede": "Scobolide",
    "Scolipede": "Brutapode",
    "Cottonee": "Doudouvet",
    "Whimsicott": "Farfaduvet",
    "Petilil": "Chlorobule",
    "Lilligant": "Fragilady",
    "Basculin": "Bargantua",
    "Sandile": "Mascaïman",
    "Krokorok": "Escroco",
    "Krookodile": "Crocorible",
    "Darumaka": "Darumarond",
    "Darmanitan": "Darumacho",
    "Maractus": "Maracachi",
    "Dwebble": "Crabicoque",
    "Crustle": "Crabaraque",
    "Scraggy": "Baggiguane",
    "Scrafty": "Baggaïd",
    "Sigilyph": "Cryptéro",
    "Yamask": "Tutafeh",
    "Cofagrigus": "Tutankafer",
    "Tirtouga": "Carapagos",
    "Carracosta": "Mégapagos",
    "Archen": "Arkéapti",
    "Archeops": "Aéroptéryx",
    "Trubbish": "Miamiasme",
    "Garbodor": "Miasmax",
    "Zorua": "Zorua",
    "Zoroark": "Zoroark",
    "Minccino": "Chinchidou",
    "Cinccino": "Pashmilla",
    "Gothita": "Scrutella",
    "Gothorita": "Mesmérella",
    "Gothitelle": "Sidérella",
    "Solosis": "Nucléos",
    "Duosion": "Méios",
    "Reuniclus": "Symbios",
    "Ducklett": "Couaneton",
    "Swanna": "Lakmécygne",
    "Vanillite": "Sorbébé",
    "Vanillish": "Sorboul",
    "Vanilluxe": "Sorbouboul",
    "Deerling": "Vivaldaim",
    "Sawsbuck": "Haydaim",
    "Emolga": "Emolga",
    "Karrablast": "Carabing",
    "Escavalier": "Lançargot",
    "Foongus": "Trompignon",
    "Amoonguss": "Gaulet",
    "Frillish": "Viskuse",
    "Jellicent": "Moyade",
    "Alomomola": "Mamanbo",
    "Joltik": "Statitik",
    "Galvantula": "Mygavolt",
    "Ferroseed": "Grindur",
    "Ferrothorn": "Noacier",
    "Klink": "Tic",
    "Klang": "Clic",
    "Klinklang": "Cliticlic",
    "Tynamo": "Anchwatt",
    "Eelektrik": "Lampéroie",
    "Eelektross": "Ohmassacre",
    "Elgyem": "Lewsor",
    "Beheeyem": "Neitram",
    "Litwick": "Funécire",
    "Lampent": "Mélancolux",
    "Chandelure": "Lugulabre",
    "Axew": "Coupenotte",
    "Fraxure": "Incisache",
    "Haxorus": "Tranchodon",
    "Cubchoo": "Polarhume",
    "Beartic": "Polagriffe",
    "Cryogonal": "Hexagel",
    "Shelmet": "Escargaume",
    "Accelgor": "Limaspeed",
    "Stunfisk": "Limonde",
    "Mienfoo": "Kungfouine",
    "Mienshao": "Shaofouine",
    "Druddigon": "Drakkarmin",
    "Golett": "Gringolem",
    "Golurk": "Golemastoc",
    "Pawniard": "Scalpion",
    "Bisharp": "Scalproie",
    "Bouffalant": "Frison",
    "Rufflet": "Furaiglon",
    "Braviary": "Gueriaigle",
    "Vullaby": "Vostourno",
    "Mandibuzz": "Vaututrice",
    "Heatmor": "Aflamanoir",
    "Durant": "Fermite",
    "Deino": "Solochi",
    "Zweilous": "Diamat",
    "Hydreigon": "Trioxhydre",
    "Larvesta": "Pyronille",
    "Volcarona": "Pyrax",
    "Cobalion": "Cobaltium",
    "Terrakion": "Terrakium",
    "Virizion": "Viridium",
    "Tornadus": "Boréas",
    "Thundurus": "Fulguris",
    "Reshiram": "Reshiram",
    "Zekrom": "Zekrom",
    "Landorus": "Démétéros",
    "Kyurem": "Kyurem",
    "Keldeo": "Keldeo",
    "Meloetta": "Meloetta",
    "Genesect": "Genesect",

    # Génération 6 (Kalos)
    "Chespin": "Marisson",
    "Quilladin": "Boguérisse",
    "Chesnaught": "Blindépique",
    "Fennekin": "Feunnec",
    "Braixen": "Roussil",
    "Delphox": "Goupelin",
    "Froakie": "Grenousse",
    "Frogadier": "Croâporal",
    "Greninja": "Amphinobi",
    "Bunnelby": "Sapereau",
    "Diggersby": "Excavarenne",
    "Fletchling": "Passerouge",
    "Fletchinder": "Braisillon",
    "Talonflame": "Flambusard",
    "Scatterbug": "Lépidonille",
    "Spewpa": "Pérégrain",
    "Vivillon": "Prismillon",
    "Litleo": "Hélionceau",
    "Pyroar": "Némélios",
    "Flabébé": "Flabébé",
    "Floette": "Floette",
    "Florges": "Florges",
    "Skiddo": "Cabriolaine",
    "Gogoat": "Chevroum",
    "Pancham": "Pandespiègle",
    "Pangoro": "Pandarbare",
    "Furfrou": "Couafarel",
    "Espurr": "Psystigri",
    "Meowstic": "Mistigrix",
    "Honedge": "Monorpale",
    "Doublade": "Dimoclès",
    "Aegislash": "Exagide",
    "Spritzee": "Vaporéon",
    "Aromatisse": "Cocotine",
    "Swirlix": "Sucroquin",
    "Slurpuff": "Cupcanaille",
    "Inkay": "Sepiatop",
    "Malamar": "Sepiatroce",
    "Binacle": "Opermine",
    "Barbaracle": "Golgopathe",
    "Skrelp": "Venalgue",
    "Dragalge": "Kravarech",
    "Clauncher": "Flingouste",
    "Clawitzer": "Gamblast",
    "Helioptile": "Galvaran",
    "Heliolisk": "Iguolta",
    "Tyrunt": "Ptyranidur",
    "Tyrantrum": "Rexillius",
    "Amaura": "Amagara",
    "Aurorus": "Dragmara",
    "Hawlucha": "Brutalibré",
    "Dedenne": "Dedenne",
    "Carbink": "Strassie",
    "Goomy": "Mucuscule",
    "Sliggoo": "Colimucus",
    "Goodra": "Muplodocus",
    "Klefki": "Trousselin",
    "Phantump": "Brocélôme",
    "Trevenant": "Desséliande",
    "Pumpkaboo": "Pitrouille",
    "Gourgeist": "Banshitrouye",
    "Bergmite": "Grelaçon",
    "Avalugg": "Séracrawl",
    "Noibat": "Sonistrelle",
    "Noivern": "Bruyverne",
    "Xerneas": "Xerneas",
    "Yveltal": "Yveltal",
    "Zygarde": "Zygarde",
    "Diancie": "Diancie",
    "Hoopa": "Hoopa",
    "Volcanion": "Volcanion",

    # Génération 7 (Alola)
    "Rowlet": "Brindibou",
    "Dartrix": "Efflèche",
    "Decidueye": "Archéduc",
    "Litten": "Flamiaou",
    "Torracat": "Matoufeu",
    "Incineroar": "Félinferno",
    "Popplio": "Otaquin",
    "Brionne": "Otarlette",
    "Primarina": "Oratoria",
    "Pikipek": "Picassaut",
    "Trumbeak": "Piclairon",
    "Toucannon": "Bazoucan",
    "Yungoos": "Manglouton",
    "Gumshoos": "Argouste",
    "Grubbin": "Larvibule",
    "Charjabug": "Chrysapile",
    "Vikavolt": "Lucanon",
    "Crabrawler": "Crabagarre",
    "Crabominable": "Crabominable",
    "Oricorio": "Plumeline",
    "Cutiefly": "Bombydou",
    "Ribombee": "Rubombelle",
    "Rockruff": "Rocabot",
    "Lycanroc": "Lougaroc",
    "Wishiwashi": "Froussardine",
    "Mareanie": "Vorastérie",
    "Toxapex": "Prédastérie",
    "Mudbray": "Tiboudet",
    "Mudsdale": "Bourrinos",
    "Dewpider": "Araqua",
    "Araquanid": "Tarenbulle",
    "Fomantis": "Mimantis",
    "Lurantis": "Floramantis",
    "Morelull": "Spododo",
    "Shiinotic": "Lampignon",
    "Salandit": "Tritox",
    "Salazzle": "Malamandre",
    "Stufful": "Nounourson",
    "Bewear": "Chelours",
    "Bounsweet": "Croquine",
    "Steenee": "Candine",
    "Tsareena": "Sucreine",
    "Comfey": "Guérilande",
    "Oranguru": "Gouroutan",
    "Passimian": "Quartermac",
    "Wimpod": "Sovkipou",
    "Golisopod": "Sarmuraï",
    "Sandygast": "Bacabouh",
    "Palossand": "Trépassable",
    "Pyukumuku": "Concombaffe",
    "Type: Null": "Type:0",
    "Silvally": "Silvallié",
    "Minior": "Météno",
    "Komala": "Dodoala",
    "Turtonator": "Boumata",
    "Togedemaru": "Togedemaru",
    "Mimikyu": "Mimiqui",
    "Bruxish": "Denticrisse",
    "Drampa": "Draïeul",
    "Dhelmise": "Sinistrail",
    "Jangmo-o": "Bébécaille",
    "Hakamo-o": "Écaïd",
    "Kommo-o": "Ékaïser",
    "Tapu Koko": "Tokorico",
    "Tapu Lele": "Tokopiyon",
    "Tapu Bulu": "Tokotoro",
    "Tapu Fini": "Tokopisco",
    "Cosmog": "Cosmog",
    "Cosmoem": "Cosmovum",
    "Solgaleo": "Solgaleo",
    "Lunala": "Lunala",
    "Nihilego": "Zéroïd",
    "Buzzwole": "Mouscoto",
    "Pheromosa": "Cancrelove",
    "Xurkitree": "Câblifère",
    "Celesteela": "Bamboiselle",
    "Kartana": "Katagami",
    "Guzzlord": "Engloutyran",
    "Necrozma": "Necrozma",
    "Magearna": "Magearna",
    "Marshadow": "Marshadow",
    "Poipole": "Vémini",
    "Naganadel": "Mandrillon",
    "Stakataka": "Ama-Ama",
    "Blacephalon": "Pierroteknik",
    "Zeraora": "Zeraora",
    "Meltan": "Meltan",
    "Melmetal": "Melmetal",

    # Génération 8 (Galar)
    "Grookey": "Ouistempo",
    "Thwackey": "Badabouin",
    "Rillaboom": "Gorythmic",
    "Scorbunny": "Flambino",
    "Raboot": "Lapyro",
    "Cinderace": "Pyrobut",
    "Sobble": "Larméléon",
    "Drizzile": "Arrozard",
    "Inteleon": "Lézargus",
    "Skwovet": "Rongourmand",
    "Greedent": "Rongrigou",
    "Rookidee": "Minisange",
    "Corvisquire": "Corvaillus",
    "Corviknight": "Corvaillus",
    "Blipbug": "Larvadar",
    "Dottler": "Coléodôme",
    "Orbeetle": "Astronelle",
    "Nickit": "Roublenard",
    "Thievul": "Roublenard",
    "Gossifleur": "Tournicoton",
    "Eldegoss": "Blancoton",
    "Wooloo": "Moumouton",
    "Dubwool": "Moumouflon",
    "Chewtle": "Khélocrok",
    "Drednaw": "Torgamord",
    "Yamper": "Voltoutou",
    "Boltund": "Fulgudog",
    "Rolycoly": "Charbi",
    "Carkol": "Wagomine",
    "Coalossal": "Monthracite",
    "Applin": "Verpom",
    "Flapple": "Pomdrapi",
    "Appletun": "Dratatin",
    "Silicobra": "Dunaja",
    "Sandaconda": "Dunaconda",
    "Cramorant": "Nigosier",
    "Arrokuda": "Embrochet",
    "Barraskewda": "Hastacuda",
    "Toxel": "Toxizap",
    "Toxtricity": "Salarsen",
    "Sizzlipede": "Grillepattes",
    "Centiskorch": "Scolocendre",
    "Clobbopus": "Poulpaf",
    "Grapploct": "Krakos",
    "Sinistea": "Théffroi",
    "Polteageist": "Polthégeist",
    "Hatenna": "Bibichut",
    "Hattrem": "Chapotus",
    "Hatterene": "Sorcilence",
    "Impidimp": "Grimalin",
    "Morgrem": "Fourbelin",
    "Grimmsnarl": "Angoliath",
    "Obstagoon": "Ixon",
    "Perrserker": "Berserkatt",
    "Cursola": "Corayôme",
    "Sirfetch'd": "Palarticho",
    "Mr. Rime": "M. Glaquette",
    "Runerigus": "Tutétékri",
    "Milcery": "Crèmy",
    "Alcremie": "Charmilly",
    "Falinks": "Hexadron",
    "Pincurchin": "Wattapik",
    "Snom": "Frissonille",
    "Frosmoth": "Beldeneige",
    "Stonjourner": "Dolman",
    "Eiscue": "Bekaglaçon",
    "Indeedee": "Wimessir",
    "Morpeko": "Morpeko",
    "Cufant": "Charibari",
    "Copperajah": "Pachyradjah",
    "Dracozolt": "Galvagon",
    "Arctozolt": "Galvagla",
    "Dracovish": "Hydragon",
    "Arctovish": "Hydragla",
    "Duraludon": "Duralugon",
    "Dreepy": "Fantyrm",
    "Drakloak": "Dispareptil",
    "Dragapult": "Lanssorien",
    "Zacian": "Zacian",
    "Zamazenta": "Zamazenta",
    "Eternatus": "Éthernatos",
    "Kubfu": "Wushours",
    "Urshifu": "Shifours",
    "Regieleki": "Regieleki",
    "Regidrago": "Regidrago",
    "Glastrier": "Blizzeval",
    "Spectrier": "Spectreval",
    "Calyrex": "Sylveroy",

    # Génération 9 (Paldea)
    "Sprigatito": "Poussacha",
    "Floragato": "Matourgeon",
    "Meowscarada": "Miascarade",
    "Fuecoco": "Chochodile",
    "Crocalor": "Crocogril",
    "Skeledirge": "Flâmigator",
    "Quaxly": "Coiffeton",
    "Quaxwell": "Canarbello",
    "Quaquaval": "Palmaval",
    "Lechonk": "Gourmelet",
    "Oinkologne": "Fragroin",
    "Tarountula": "Tissenboule",
    "Spidops": "Filentrappe",
    "Nymble": "Lilliterr",
    "Lokix": "Gambex",
    "Pawmi": "Pohm",
    "Pawmo": "Pohmpote",
    "Pawmot": "Pohmarmotte",
    "Tandemaus": "Compagnol",
    "Maushold": "Famignol",
    "Fidough": "Pâtachiot",
    "Dachsbun": "Briochien",
    "Smoliv": "Olivini",
    "Dolliv": "Olivado",
    "Arboliva": "Arboliva",
    "Squawkabilly": "Tapatoès",
    "Nacli": "Selutin",
    "Naclstack": "Amonsel",
    "Garganacl": "Gigansel",
    "Charcadet": "Charbambin",
    "Armarouge": "Carmadura",
    "Ceruledge": "Malvalame",
    "Tadbulb": "Ampibidou",
    "Bellibolt": "Amphinobi",
    "Wattrel": "Zapétrel",
    "Kilowattrel": "Fulgulairo",
    "Maschiff": "Mabostiff",
    "Mabosstiff": "Mastouffe",
    "Shroodle": "Gribouraigne",
    "Grafaiai": "Tag-Tag",
    "Bramblin": "Virovent",
    "Brambleghast": "Virevorreur",
    "Toedscool": "Terracool",
    "Toedscruel": "Terracruel",
    "Klawf": "Craparoi",
    "Capsakid": "Pimito",
    "Scovillain": "Scovilain",
    "Rellor": "Léboulin",
    "Rabsca": "Bérasca",
    "Flittle": "Flotajou",
    "Espathra": "Cléopsytra",
    "Tinkatink": "Forgerette",
    "Tinkatuff": "Forgella",
    "Tinkaton": "Forgelina",
    "Wiglett": "Taupikeau",
    "Wugtrio": "Triopikeau",
    "Bombirdier": "Lestombaile",
    "Finizen": "Dofin",
    "Palafin": "Superdofin",
    "Varoom": "Vrombi",
    "Revavroom": "Vrombotor",
    "Cyclizar": "Motorizard",
    "Orthworm": "Ferdeter",
    "Glimmet": "Germéclat",
    "Glimmora": "Floréclat",
    "Greavard": "Toutombe",
    "Houndstone": "Tomberro",
    "Flamigo": "Flamenroule",
    "Cetoddle": "Piétacé",
    "Cetitan": "Balbalèze",
    "Veluza": "Délestin",
    "Dondozo": "Oyacata",
    "Tatsugiri": "Nigirigon",
    "Annihilape": "Courrousinge",
    "Clodsire": "Clodsire",
    "Farigiraf": "Farigiraf",
    "Dudunsparce": "Deusolourdo",
    "Kingambit": "Kingambit",
    "Great Tusk": "Fort-Ivoire",
    "Scream Tail": "Hurle-Queue",
    "Brute Bonnet": "Fongus-Rage",
    "Flutter Mane": "Flotte-Mèche",
    "Slither Wing": "Rampe-Ailes",
    "Sandy Shocks": "Sable-Choc",
    "Iron Treads": "Roue-Fer",
    "Iron Bundle": "Hotte-Fer",
    "Iron Hands": "Paume-Fer",
    "Iron Jugulis": "Têtes-Fer",
    "Iron Moth": "Mite-Fer",
    "Iron Thorns": "Épine-Fer",
    "Frigibax": "Frigodo",
    "Arctibax": "Cryodo",
    "Baxcalibur": "Glaivodo",
    "Gimmighoul": "Mordudor",
    "Gholdengo": "Gromago",
    "Wo-Chien": "Chongjian",
    "Chien-Pao": "Baojian",
    "Ting-Lu": "Dinglu",
    "Chi-Yu": "Yuyu",
    "Roaring Moon": "Rugit-Lune",
    "Iron Valiant": "Garde-Fer",
    "Koraidon": "Koraidon",
    "Miraidon": "Miraidon",
    "Walking Wake": "Sillage-Aqua",
    "Iron Leaves": "Feuille-Fer",
    "Dipplin": "Pomdorochi",
    "Poltchageist": "Poltchageist",
    "Sinistcha": "Sinistcha",
    "Okidogi": "Félicanis",
    "Munkidori": "Fortusimia",
    "Fezandipiti": "Favianos",
    "Ogerpon": "Ogerpon",
    "Archaludon": "Pondralugon",
    "Hydrapple": "Dipplinala",
    "Gouging Fire": "Feu-Perçant",
    "Raging Bolt": "Ire-Foudre",
    "Iron Boulder": "Roc-Fer",
    "Iron Crown": "Chef-Fer",
    "Terapagos": "Terapagos",
    "Pecharunt": "Pêchaminus",

    # Formes alternatives et variantes spéciales
    "Sylveon": "Nymphali",
    "Kleavor": "Hachécateur",
    "Wyrdeer": "Cerbyllin",
    "Basculegion": "Paragruel",
    "Sneasler": "Farfurex",
    "Overqwil": "Qwilpik",
    "Enamorus": "Démétéros",
    "Ursaluna": "Ursaking",
    "Cursola": "Corayôme",
    "Mr. Rime": "M. Glaquette",
    "Runerigus": "Tutétékri",
}

def translate_pokemon_names_in_file(file_path):
    """
    Traduit tous les noms de Pokémon dans un fichier.
    """
    print(f"Traitement du fichier: {file_path}")
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except UnicodeDecodeError:
        with open(file_path, 'r', encoding='latin-1') as f:
            content = f.read()
    
    original_content = content
    changes_made = 0
    
    # Pattern pour trouver les .speciesName = _("nom")
    pattern = r'\.speciesName = _\("([^"]+)"\)'
    
    def replace_name(match):
        nonlocal changes_made
        original_name = match.group(1)
        
        if original_name in POKEMON_TRANSLATIONS:
            french_name = POKEMON_TRANSLATIONS[original_name]
            if french_name != original_name:  # Seulement compter si c'est vraiment un changement
                changes_made += 1
                print(f"  {original_name} → {french_name}")
            return f'.speciesName = _("{french_name}")'
        else:
            print(f"  ⚠️  Nom non trouvé dans la liste: {original_name}")
            return match.group(0)  # Garder l'original
    
    # Remplacer tous les noms
    content = re.sub(pattern, replace_name, content)
    
    # Sauvegarder seulement si des changements ont été faits
    if content != original_content:
        try:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"  ✅ {changes_made} changements sauvegardés dans {file_path}")
        except Exception as e:
            print(f"  ❌ Erreur lors de la sauvegarde: {e}")
    else:
        print(f"  ℹ️  Aucun changement nécessaire dans {file_path}")
    
    return changes_made

def main():
    """
    Fonction principale pour traduire tous les fichiers species_info.
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))
    species_info_dir = os.path.join(script_dir, "src", "data", "pokemon", "species_info")
    
    if not os.path.exists(species_info_dir):
        print(f"❌ Répertoire non trouvé: {species_info_dir}")
        return 1
    
    total_changes = 0
    files_processed = 0
    
    # Traiter tous les fichiers *families.h
    for filename in os.listdir(species_info_dir):
        if filename.endswith("families.h"):
            file_path = os.path.join(species_info_dir, filename)
            changes = translate_pokemon_names_in_file(file_path)
            total_changes += changes
            files_processed += 1
    
    print(f"\n📊 Résumé:")
    print(f"   Fichiers traités: {files_processed}")
    print(f"   Traductions effectuées: {total_changes}")
    print(f"   ✅ Traduction terminée!")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())
